// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvbSntXc5B9ecCEoLB9U3w4Gl9-DnqSGs',
    appId: '1:334959934556:web:944a0eb248b9ef04dbfa99',
    messagingSenderId: '334959934556',
    projectId: 'tanken-adak-app',
    authDomain: 'tanken-adak-app.firebaseapp.com',
    storageBucket: 'tanken-adak-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6TpV47Pu2LYj-1E2mLji_Q4vyfCdW4cc',
    appId: '1:334959934556:android:f2f82315838eaba3dbfa99',
    messagingSenderId: '334959934556',
    projectId: 'tanken-adak-app',
    storageBucket: 'tanken-adak-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJUDUI-vbpRsvomv3eBV2cF__e-X4yThQ',
    appId: '1:334959934556:ios:84d65e170a2433dadbfa99',
    messagingSenderId: '334959934556',
    projectId: 'tanken-adak-app',
    storageBucket: 'tanken-adak-app.firebasestorage.app',
    iosBundleId: 'com.example.tenkenAdak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJUDUI-vbpRsvomv3eBV2cF__e-X4yThQ',
    appId: '1:334959934556:ios:84d65e170a2433dadbfa99',
    messagingSenderId: '334959934556',
    projectId: 'tanken-adak-app',
    storageBucket: 'tanken-adak-app.firebasestorage.app',
    iosBundleId: 'com.example.tenkenAdak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvbSntXc5B9ecCEoLB9U3w4Gl9-DnqSGs',
    appId: '1:334959934556:web:43d8342caf1721cfdbfa99',
    messagingSenderId: '334959934556',
    projectId: 'tanken-adak-app',
    authDomain: 'tanken-adak-app.firebaseapp.com',
    storageBucket: 'tanken-adak-app.firebasestorage.app',
  );
}
